import 'dart:convert';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:http/http.dart' as http;
import 'package:weather/models/city_model.dart';

class ForecastWeatherApi {
  Future<String> getWeather({bool debug = false, required City city}) async {
    final String API_KEY = dotenv.env['API_KEY'] ?? "";
    if (!debug && API_KEY == "") throw Exception("Brakuje klucza API!");

    final String apikey = API_KEY;
    final url = Uri.https("api.openweathermap.org", "/data/2.5/forecast", {
      'lat': city.lat.toString(),
      'lon': city.lon.toString(),
      'units': 'metric',
      'appid': apikey,
    });
    if (!debug) {
      final response = await http.get(url);

      if (response.statusCode != 200) {
        // print("FAILED" + response.body);
        throw Exception("Failed to get data: $response");
      }
      return response.body;
    }

    print("DEBUG");
    await Future.delayed(Duration(seconds: 1));
    final response = {
      "cod": "200",
      "message": 0,
      "cnt": 40,
      "list": [
        {
          "dt": 1784980800,
          "main": {
            "temp": 24.49,
            "feels_like": 24.27,
            "temp_min": 24.49,
            "temp_max": 25.43,
            "pressure": 1009,
            "sea_level": 1009,
            "grnd_level": 999,
            "humidity": 49,
            "temp_kf": -0.94,
            "dew_point": 13.09,
          },
          "weather": [
            {
              "id": 804,
              "main": "Clouds",
              "description": "overcast clouds",
              "icon": "04d",
            },
          ],
          "clouds": {"all": 97},
          "wind": {"speed": 3.9, "deg": 227, "gust": 5.48},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-25 12:00:00",
        },
        {
          "dt": 1784991600,
          "main": {
            "temp": 26.04,
            "feels_like": 26.04,
            "temp_min": 26.04,
            "temp_max": 29.13,
            "pressure": 1008,
            "sea_level": 1008,
            "grnd_level": 998,
            "humidity": 44,
            "temp_kf": -3.09,
            "dew_point": 12.85,
          },
          "weather": [
            {
              "id": 804,
              "main": "Clouds",
              "description": "overcast clouds",
              "icon": "04d",
            },
          ],
          "clouds": {"all": 89},
          "wind": {"speed": 3.96, "deg": 221, "gust": 6.05},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-25 15:00:00",
        },
        {
          "dt": 1785002400,
          "main": {
            "temp": 24.42,
            "feels_like": 24.09,
            "temp_min": 24.38,
            "temp_max": 24.42,
            "pressure": 1007,
            "sea_level": 1007,
            "grnd_level": 997,
            "humidity": 45,
            "temp_kf": 0.04,
            "dew_point": 11.73,
          },
          "weather": [
            {
              "id": 803,
              "main": "Clouds",
              "description": "broken clouds",
              "icon": "04d",
            },
          ],
          "clouds": {"all": 58},
          "wind": {"speed": 2.77, "deg": 216, "gust": 4.45},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-25 18:00:00",
        },
        {
          "dt": 1785013200,
          "main": {
            "temp": 19.7,
            "feels_like": 19.03,
            "temp_min": 19.7,
            "temp_max": 19.7,
            "pressure": 1005,
            "sea_level": 1005,
            "grnd_level": 996,
            "humidity": 50,
            "temp_kf": 0,
            "dew_point": 8.95,
          },
          "weather": [
            {
              "id": 803,
              "main": "Clouds",
              "description": "broken clouds",
              "icon": "04n",
            },
          ],
          "clouds": {"all": 51},
          "wind": {"speed": 3.14, "deg": 185, "gust": 4.61},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "n"},
          "dt_txt": "2026-07-25 21:00:00",
        },
        {
          "dt": 1785024000,
          "main": {
            "temp": 18.38,
            "feels_like": 17.74,
            "temp_min": 18.38,
            "temp_max": 18.38,
            "pressure": 1005,
            "sea_level": 1005,
            "grnd_level": 996,
            "humidity": 56,
            "temp_kf": 0,
            "dew_point": 8.88,
          },
          "weather": [
            {
              "id": 802,
              "main": "Clouds",
              "description": "scattered clouds",
              "icon": "03n",
            },
          ],
          "clouds": {"all": 41},
          "wind": {"speed": 3.23, "deg": 179, "gust": 5.3},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "n"},
          "dt_txt": "2026-07-26 00:00:00",
        },
        {
          "dt": 1785034800,
          "main": {
            "temp": 17.35,
            "feels_like": 16.73,
            "temp_min": 17.35,
            "temp_max": 17.35,
            "pressure": 1004,
            "sea_level": 1004,
            "grnd_level": 995,
            "humidity": 61,
            "temp_kf": 0,
            "dew_point": 9.17,
          },
          "weather": [
            {
              "id": 800,
              "main": "Clear",
              "description": "clear sky",
              "icon": "01n",
            },
          ],
          "clouds": {"all": 1},
          "wind": {"speed": 2.99, "deg": 204, "gust": 4.74},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "n"},
          "dt_txt": "2026-07-26 03:00:00",
        },
        {
          "dt": 1785045600,
          "main": {
            "temp": 22.42,
            "feels_like": 22.13,
            "temp_min": 22.42,
            "temp_max": 22.42,
            "pressure": 1005,
            "sea_level": 1005,
            "grnd_level": 995,
            "humidity": 54,
            "temp_kf": 0,
            "dew_point": 11.1,
          },
          "weather": [
            {
              "id": 802,
              "main": "Clouds",
              "description": "scattered clouds",
              "icon": "03d",
            },
          ],
          "clouds": {"all": 46},
          "wind": {"speed": 2.35, "deg": 246, "gust": 3.63},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-26 06:00:00",
        },
        {
          "dt": 1785056400,
          "main": {
            "temp": 28.21,
            "feels_like": 27.78,
            "temp_min": 28.21,
            "temp_max": 28.21,
            "pressure": 1004,
            "sea_level": 1004,
            "grnd_level": 995,
            "humidity": 39,
            "temp_kf": 0,
            "dew_point": 11.73,
          },
          "weather": [
            {
              "id": 804,
              "main": "Clouds",
              "description": "overcast clouds",
              "icon": "04d",
            },
          ],
          "clouds": {"all": 97},
          "wind": {"speed": 2.02, "deg": 272, "gust": 2.15},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-26 09:00:00",
        },
        {
          "dt": 1785067200,
          "main": {
            "temp": 30.44,
            "feels_like": 29.34,
            "temp_min": 30.44,
            "temp_max": 30.44,
            "pressure": 1003,
            "sea_level": 1003,
            "grnd_level": 994,
            "humidity": 32,
            "temp_kf": 0,
            "dew_point": 11.12,
          },
          "weather": [
            {
              "id": 804,
              "main": "Clouds",
              "description": "overcast clouds",
              "icon": "04d",
            },
          ],
          "clouds": {"all": 94},
          "wind": {"speed": 3.02, "deg": 230, "gust": 5.83},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-26 12:00:00",
        },
        {
          "dt": 1785078000,
          "main": {
            "temp": 31.16,
            "feels_like": 30,
            "temp_min": 31.16,
            "temp_max": 31.16,
            "pressure": 1002,
            "sea_level": 1002,
            "grnd_level": 993,
            "humidity": 31,
            "temp_kf": 0,
            "dew_point": 10.68,
          },
          "weather": [
            {
              "id": 804,
              "main": "Clouds",
              "description": "overcast clouds",
              "icon": "04d",
            },
          ],
          "clouds": {"all": 99},
          "wind": {"speed": 4.81, "deg": 219, "gust": 6.78},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-26 15:00:00",
        },
        {
          "dt": 1785088800,
          "main": {
            "temp": 23.13,
            "feels_like": 23.04,
            "temp_min": 23.13,
            "temp_max": 23.13,
            "pressure": 1002,
            "sea_level": 1002,
            "grnd_level": 993,
            "humidity": 59,
            "temp_kf": 0,
            "dew_point": 13.68,
          },
          "weather": [
            {
              "id": 500,
              "main": "Rain",
              "description": "light rain",
              "icon": "10d",
            },
          ],
          "clouds": {"all": 99},
          "wind": {"speed": 3.11, "deg": 191, "gust": 4.8},
          "visibility": 10000,
          "pop": 0.2,
          "rain": {"3h": 0.15},
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-26 18:00:00",
        },
        {
          "dt": 1785099600,
          "main": {
            "temp": 17.56,
            "feels_like": 17.54,
            "temp_min": 17.56,
            "temp_max": 17.56,
            "pressure": 1004,
            "sea_level": 1004,
            "grnd_level": 995,
            "humidity": 83,
            "temp_kf": 0,
            "dew_point": 14.53,
          },
          "weather": [
            {
              "id": 500,
              "main": "Rain",
              "description": "light rain",
              "icon": "10n",
            },
          ],
          "clouds": {"all": 75},
          "wind": {"speed": 4.52, "deg": 346, "gust": 9.92},
          "visibility": 10000,
          "pop": 0.27,
          "rain": {"3h": 0.2},
          "sys": {"pod": "n"},
          "dt_txt": "2026-07-26 21:00:00",
        },
        {
          "dt": 1785110400,
          "main": {
            "temp": 18.06,
            "feels_like": 18.11,
            "temp_min": 18.06,
            "temp_max": 18.06,
            "pressure": 1004,
            "sea_level": 1004,
            "grnd_level": 995,
            "humidity": 84,
            "temp_kf": 0,
            "dew_point": 14.69,
          },
          "weather": [
            {
              "id": 500,
              "main": "Rain",
              "description": "light rain",
              "icon": "10n",
            },
          ],
          "clouds": {"all": 81},
          "wind": {"speed": 2.26, "deg": 244, "gust": 3.51},
          "visibility": 10000,
          "pop": 0.53,
          "rain": {"3h": 0.39},
          "sys": {"pod": "n"},
          "dt_txt": "2026-07-27 00:00:00",
        },
        {
          "dt": 1785121200,
          "main": {
            "temp": 16.35,
            "feels_like": 16.47,
            "temp_min": 16.35,
            "temp_max": 16.35,
            "pressure": 1004,
            "sea_level": 1004,
            "grnd_level": 995,
            "humidity": 93,
            "temp_kf": 0,
            "dew_point": 15.24,
          },
          "weather": [
            {
              "id": 500,
              "main": "Rain",
              "description": "light rain",
              "icon": "10n",
            },
          ],
          "clouds": {"all": 100},
          "wind": {"speed": 4.31, "deg": 239, "gust": 11.78},
          "visibility": 10000,
          "pop": 1,
          "rain": {"3h": 2.1},
          "sys": {"pod": "n"},
          "dt_txt": "2026-07-27 03:00:00",
        },
        {
          "dt": 1785132000,
          "main": {
            "temp": 18.16,
            "feels_like": 18.22,
            "temp_min": 18.16,
            "temp_max": 18.16,
            "pressure": 1005,
            "sea_level": 1005,
            "grnd_level": 995,
            "humidity": 84,
            "temp_kf": 0,
            "dew_point": 15.54,
          },
          "weather": [
            {
              "id": 500,
              "main": "Rain",
              "description": "light rain",
              "icon": "10d",
            },
          ],
          "clouds": {"all": 100},
          "wind": {"speed": 7.05, "deg": 241, "gust": 11.15},
          "visibility": 10000,
          "pop": 1,
          "rain": {"3h": 0.86},
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-27 06:00:00",
        },
        {
          "dt": 1785142800,
          "main": {
            "temp": 17.3,
            "feels_like": 17.25,
            "temp_min": 17.3,
            "temp_max": 17.3,
            "pressure": 1007,
            "sea_level": 1007,
            "grnd_level": 997,
            "humidity": 83,
            "temp_kf": 0,
            "dew_point": 14.42,
          },
          "weather": [
            {
              "id": 500,
              "main": "Rain",
              "description": "light rain",
              "icon": "10d",
            },
          ],
          "clouds": {"all": 94},
          "wind": {"speed": 6.2, "deg": 282, "gust": 10.12},
          "visibility": 10000,
          "pop": 1,
          "rain": {"3h": 1.81},
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-27 09:00:00",
        },
        {
          "dt": 1785153600,
          "main": {
            "temp": 21.66,
            "feels_like": 21.27,
            "temp_min": 21.66,
            "temp_max": 21.66,
            "pressure": 1008,
            "sea_level": 1008,
            "grnd_level": 998,
            "humidity": 53,
            "temp_kf": 0,
            "dew_point": 11.52,
          },
          "weather": [
            {
              "id": 500,
              "main": "Rain",
              "description": "light rain",
              "icon": "10d",
            },
          ],
          "clouds": {"all": 73},
          "wind": {"speed": 8.82, "deg": 285, "gust": 11.67},
          "visibility": 10000,
          "pop": 1,
          "rain": {"3h": 0.78},
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-27 12:00:00",
        },
        {
          "dt": 1785164400,
          "main": {
            "temp": 20.51,
            "feels_like": 20,
            "temp_min": 20.51,
            "temp_max": 20.51,
            "pressure": 1011,
            "sea_level": 1011,
            "grnd_level": 1001,
            "humidity": 53,
            "temp_kf": 0,
            "dew_point": 10.7,
          },
          "weather": [
            {
              "id": 500,
              "main": "Rain",
              "description": "light rain",
              "icon": "10d",
            },
          ],
          "clouds": {"all": 66},
          "wind": {"speed": 8.81, "deg": 313, "gust": 12.43},
          "visibility": 10000,
          "pop": 0.51,
          "rain": {"3h": 0.34},
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-27 15:00:00",
        },
        {
          "dt": 1785175200,
          "main": {
            "temp": 19.06,
            "feels_like": 18.17,
            "temp_min": 19.06,
            "temp_max": 19.06,
            "pressure": 1012,
            "sea_level": 1012,
            "grnd_level": 1003,
            "humidity": 44,
            "temp_kf": 0,
            "dew_point": 6.64,
          },
          "weather": [
            {
              "id": 803,
              "main": "Clouds",
              "description": "broken clouds",
              "icon": "04d",
            },
          ],
          "clouds": {"all": 59},
          "wind": {"speed": 4.69, "deg": 320, "gust": 8.34},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-27 18:00:00",
        },
        {
          "dt": 1785186000,
          "main": {
            "temp": 15.75,
            "feels_like": 14.87,
            "temp_min": 15.75,
            "temp_max": 15.75,
            "pressure": 1015,
            "sea_level": 1015,
            "grnd_level": 1005,
            "humidity": 57,
            "temp_kf": 0,
            "dew_point": 7.21,
          },
          "weather": [
            {
              "id": 803,
              "main": "Clouds",
              "description": "broken clouds",
              "icon": "04n",
            },
          ],
          "clouds": {"all": 75},
          "wind": {"speed": 3.41, "deg": 293, "gust": 6.54},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "n"},
          "dt_txt": "2026-07-27 21:00:00",
        },
        {
          "dt": 1785196800,
          "main": {
            "temp": 13.08,
            "feels_like": 12.17,
            "temp_min": 13.08,
            "temp_max": 13.08,
            "pressure": 1016,
            "sea_level": 1016,
            "grnd_level": 1006,
            "humidity": 66,
            "temp_kf": 0,
            "dew_point": 6.94,
          },
          "weather": [
            {
              "id": 802,
              "main": "Clouds",
              "description": "scattered clouds",
              "icon": "03n",
            },
          ],
          "clouds": {"all": 46},
          "wind": {"speed": 3.81, "deg": 289, "gust": 10.29},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "n"},
          "dt_txt": "2026-07-28 00:00:00",
        },
        {
          "dt": 1785207600,
          "main": {
            "temp": 11.42,
            "feels_like": 10.55,
            "temp_min": 11.42,
            "temp_max": 11.42,
            "pressure": 1018,
            "sea_level": 1018,
            "grnd_level": 1008,
            "humidity": 74,
            "temp_kf": 0,
            "dew_point": 6.87,
          },
          "weather": [
            {
              "id": 800,
              "main": "Clear",
              "description": "clear sky",
              "icon": "01n",
            },
          ],
          "clouds": {"all": 0},
          "wind": {"speed": 4.3, "deg": 275, "gust": 10.9},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "n"},
          "dt_txt": "2026-07-28 03:00:00",
        },
        {
          "dt": 1785218400,
          "main": {
            "temp": 14.79,
            "feels_like": 14.02,
            "temp_min": 14.79,
            "temp_max": 14.79,
            "pressure": 1019,
            "sea_level": 1019,
            "grnd_level": 1010,
            "humidity": 65,
            "temp_kf": 0,
            "dew_point": 8.37,
          },
          "weather": [
            {
              "id": 800,
              "main": "Clear",
              "description": "clear sky",
              "icon": "01d",
            },
          ],
          "clouds": {"all": 1},
          "wind": {"speed": 5.96, "deg": 284, "gust": 10.16},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-28 06:00:00",
        },
        {
          "dt": 1785229200,
          "main": {
            "temp": 19.67,
            "feels_like": 18.97,
            "temp_min": 19.67,
            "temp_max": 19.67,
            "pressure": 1020,
            "sea_level": 1020,
            "grnd_level": 1010,
            "humidity": 49,
            "temp_kf": 0,
            "dew_point": 8.61,
          },
          "weather": [
            {
              "id": 800,
              "main": "Clear",
              "description": "clear sky",
              "icon": "01d",
            },
          ],
          "clouds": {"all": 7},
          "wind": {"speed": 6.62, "deg": 283, "gust": 9.14},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-28 09:00:00",
        },
        {
          "dt": 1785240000,
          "main": {
            "temp": 20.82,
            "feels_like": 20.21,
            "temp_min": 20.82,
            "temp_max": 20.82,
            "pressure": 1020,
            "sea_level": 1020,
            "grnd_level": 1010,
            "humidity": 48,
            "temp_kf": 0,
            "dew_point": 9.5,
          },
          "weather": [
            {
              "id": 802,
              "main": "Clouds",
              "description": "scattered clouds",
              "icon": "03d",
            },
          ],
          "clouds": {"all": 36},
          "wind": {"speed": 6.98, "deg": 282, "gust": 9.36},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-28 12:00:00",
        },
        {
          "dt": 1785250800,
          "main": {
            "temp": 21.71,
            "feels_like": 21.19,
            "temp_min": 21.71,
            "temp_max": 21.71,
            "pressure": 1020,
            "sea_level": 1020,
            "grnd_level": 1010,
            "humidity": 48,
            "temp_kf": 0,
            "dew_point": 10.05,
          },
          "weather": [
            {
              "id": 803,
              "main": "Clouds",
              "description": "broken clouds",
              "icon": "04d",
            },
          ],
          "clouds": {"all": 78},
          "wind": {"speed": 5.51, "deg": 297, "gust": 8.94},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-28 15:00:00",
        },
        {
          "dt": 1785261600,
          "main": {
            "temp": 19.01,
            "feels_like": 18.51,
            "temp_min": 19.01,
            "temp_max": 19.01,
            "pressure": 1020,
            "sea_level": 1020,
            "grnd_level": 1011,
            "humidity": 59,
            "temp_kf": 0,
            "dew_point": 10.81,
          },
          "weather": [
            {
              "id": 803,
              "main": "Clouds",
              "description": "broken clouds",
              "icon": "04d",
            },
          ],
          "clouds": {"all": 59},
          "wind": {"speed": 3.51, "deg": 269, "gust": 7.28},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-28 18:00:00",
        },
        {
          "dt": 1785272400,
          "main": {
            "temp": 18.09,
            "feels_like": 17.44,
            "temp_min": 18.09,
            "temp_max": 18.09,
            "pressure": 1021,
            "sea_level": 1021,
            "grnd_level": 1012,
            "humidity": 57,
            "temp_kf": 0,
            "dew_point": 9.53,
          },
          "weather": [
            {
              "id": 803,
              "main": "Clouds",
              "description": "broken clouds",
              "icon": "04n",
            },
          ],
          "clouds": {"all": 77},
          "wind": {"speed": 2.47, "deg": 288, "gust": 4.47},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "n"},
          "dt_txt": "2026-07-28 21:00:00",
        },
        {
          "dt": 1785283200,
          "main": {
            "temp": 15.64,
            "feels_like": 14.96,
            "temp_min": 15.64,
            "temp_max": 15.64,
            "pressure": 1021,
            "sea_level": 1021,
            "grnd_level": 1012,
            "humidity": 65,
            "temp_kf": 0,
            "dew_point": 9.08,
          },
          "weather": [
            {
              "id": 803,
              "main": "Clouds",
              "description": "broken clouds",
              "icon": "04n",
            },
          ],
          "clouds": {"all": 69},
          "wind": {"speed": 2.77, "deg": 266, "gust": 3.52},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "n"},
          "dt_txt": "2026-07-29 00:00:00",
        },
        {
          "dt": 1785294000,
          "main": {
            "temp": 14.23,
            "feels_like": 13.82,
            "temp_min": 14.23,
            "temp_max": 14.23,
            "pressure": 1021,
            "sea_level": 1021,
            "grnd_level": 1011,
            "humidity": 81,
            "temp_kf": 0,
            "dew_point": 11.06,
          },
          "weather": [
            {
              "id": 800,
              "main": "Clear",
              "description": "clear sky",
              "icon": "01n",
            },
          ],
          "clouds": {"all": 0},
          "wind": {"speed": 2.47, "deg": 276, "gust": 3.03},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "n"},
          "dt_txt": "2026-07-29 03:00:00",
        },
        {
          "dt": 1785304800,
          "main": {
            "temp": 17.86,
            "feels_like": 17.45,
            "temp_min": 17.86,
            "temp_max": 17.86,
            "pressure": 1022,
            "sea_level": 1022,
            "grnd_level": 1012,
            "humidity": 67,
            "temp_kf": 0,
            "dew_point": 11.74,
          },
          "weather": [
            {
              "id": 802,
              "main": "Clouds",
              "description": "scattered clouds",
              "icon": "03d",
            },
          ],
          "clouds": {"all": 35},
          "wind": {"speed": 2.13, "deg": 261, "gust": 4.14},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-29 06:00:00",
        },
        {
          "dt": 1785315600,
          "main": {
            "temp": 24.42,
            "feels_like": 24.17,
            "temp_min": 24.42,
            "temp_max": 24.42,
            "pressure": 1021,
            "sea_level": 1021,
            "grnd_level": 1012,
            "humidity": 48,
            "temp_kf": 0,
            "dew_point": 12.96,
          },
          "weather": [
            {
              "id": 802,
              "main": "Clouds",
              "description": "scattered clouds",
              "icon": "03d",
            },
          ],
          "clouds": {"all": 44},
          "wind": {"speed": 3.44, "deg": 276, "gust": 5.15},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-29 09:00:00",
        },
        {
          "dt": 1785326400,
          "main": {
            "temp": 27.13,
            "feels_like": 27.01,
            "temp_min": 27.13,
            "temp_max": 27.13,
            "pressure": 1020,
            "sea_level": 1020,
            "grnd_level": 1011,
            "humidity": 41,
            "temp_kf": 0,
            "dew_point": 12.91,
          },
          "weather": [
            {
              "id": 803,
              "main": "Clouds",
              "description": "broken clouds",
              "icon": "04d",
            },
          ],
          "clouds": {"all": 72},
          "wind": {"speed": 3.83, "deg": 287, "gust": 5.22},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-29 12:00:00",
        },
        {
          "dt": 1785337200,
          "main": {
            "temp": 28,
            "feels_like": 27.6,
            "temp_min": 28,
            "temp_max": 28,
            "pressure": 1020,
            "sea_level": 1020,
            "grnd_level": 1010,
            "humidity": 39,
            "temp_kf": 0,
            "dew_point": 12.87,
          },
          "weather": [
            {
              "id": 804,
              "main": "Clouds",
              "description": "overcast clouds",
              "icon": "04d",
            },
          ],
          "clouds": {"all": 98},
          "wind": {"speed": 3.25, "deg": 288, "gust": 4.23},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-29 15:00:00",
        },
        {
          "dt": 1785348000,
          "main": {
            "temp": 24.86,
            "feels_like": 24.73,
            "temp_min": 24.86,
            "temp_max": 24.86,
            "pressure": 1020,
            "sea_level": 1020,
            "grnd_level": 1010,
            "humidity": 51,
            "temp_kf": 0,
            "dew_point": 14.03,
          },
          "weather": [
            {
              "id": 804,
              "main": "Clouds",
              "description": "overcast clouds",
              "icon": "04d",
            },
          ],
          "clouds": {"all": 99},
          "wind": {"speed": 2.33, "deg": 302, "gust": 2.05},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-29 18:00:00",
        },
        {
          "dt": 1785358800,
          "main": {
            "temp": 20.97,
            "feels_like": 20.74,
            "temp_min": 20.97,
            "temp_max": 20.97,
            "pressure": 1021,
            "sea_level": 1021,
            "grnd_level": 1011,
            "humidity": 62,
            "temp_kf": 0,
            "dew_point": 13.43,
          },
          "weather": [
            {
              "id": 804,
              "main": "Clouds",
              "description": "overcast clouds",
              "icon": "04n",
            },
          ],
          "clouds": {"all": 100},
          "wind": {"speed": 0.9, "deg": 46, "gust": 1.24},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "n"},
          "dt_txt": "2026-07-29 21:00:00",
        },
        {
          "dt": 1785369600,
          "main": {
            "temp": 19.15,
            "feels_like": 18.9,
            "temp_min": 19.15,
            "temp_max": 19.15,
            "pressure": 1021,
            "sea_level": 1021,
            "grnd_level": 1011,
            "humidity": 68,
            "temp_kf": 0,
            "dew_point": 13.27,
          },
          "weather": [
            {
              "id": 803,
              "main": "Clouds",
              "description": "broken clouds",
              "icon": "04n",
            },
          ],
          "clouds": {"all": 76},
          "wind": {"speed": 0.64, "deg": 112, "gust": 1.19},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "n"},
          "dt_txt": "2026-07-30 00:00:00",
        },
        {
          "dt": 1785380400,
          "main": {
            "temp": 17.92,
            "feels_like": 17.7,
            "temp_min": 17.92,
            "temp_max": 17.92,
            "pressure": 1020,
            "sea_level": 1020,
            "grnd_level": 1011,
            "humidity": 74,
            "temp_kf": 0,
            "dew_point": 13.19,
          },
          "weather": [
            {
              "id": 800,
              "main": "Clear",
              "description": "clear sky",
              "icon": "01n",
            },
          ],
          "clouds": {"all": 3},
          "wind": {"speed": 1.49, "deg": 54, "gust": 1.43},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "n"},
          "dt_txt": "2026-07-30 03:00:00",
        },
        {
          "dt": 1785391200,
          "main": {
            "temp": 22.26,
            "feels_like": 22.08,
            "temp_min": 22.26,
            "temp_max": 22.26,
            "pressure": 1021,
            "sea_level": 1021,
            "grnd_level": 1011,
            "humidity": 59,
            "temp_kf": 0,
            "dew_point": 14.02,
          },
          "weather": [
            {
              "id": 801,
              "main": "Clouds",
              "description": "few clouds",
              "icon": "02d",
            },
          ],
          "clouds": {"all": 11},
          "wind": {"speed": 1.76, "deg": 104, "gust": 1.8},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-30 06:00:00",
        },
        {
          "dt": 1785402000,
          "main": {
            "temp": 27.83,
            "feels_like": 27.79,
            "temp_min": 27.83,
            "temp_max": 27.83,
            "pressure": 1021,
            "sea_level": 1021,
            "grnd_level": 1011,
            "humidity": 44,
            "temp_kf": 0,
            "dew_point": 14.47,
          },
          "weather": [
            {
              "id": 802,
              "main": "Clouds",
              "description": "scattered clouds",
              "icon": "03d",
            },
          ],
          "clouds": {"all": 39},
          "wind": {"speed": 1.2, "deg": 181, "gust": 1.37},
          "visibility": 10000,
          "pop": 0,
          "sys": {"pod": "d"},
          "dt_txt": "2026-07-30 09:00:00",
        },
      ],
      "city": {
        "id": 3088171,
        "name": "Poznań",
        "coord": {"lat": 52.4, "lon": 16.9},
        "country": "PL",
        "population": 570352,
        "timezone": 7200,
        "sunrise": 1784948489,
        "sunset": 1785005762,
      },
    };
    final output = jsonEncode(response);
    return output;
  }
}
